### ISSUE TITLE
Interoperability with vanilla HTML partials - allow to have more than one <script> tags in top level of Single-File Components

### ISSUE THREAD

**Issue by zlamma** [ractivejs/component-spec#14]
I realize this is late in the game, but I really hate to learn on my own skin how Ractive, while being **the absolute best** at bringing 2-way-binding and modularity as just a next step from the 'good old HTML+JS+CSS', still has this rough edge of only allowing a single top level `<script>` element on single-file components [here](https://github.com/ractivejs/rcu/blob/master/src/parse.js#L44).
I mean, if not for this one, you really could treat pretty much every HTML content as a starting point for a Ractive component. But here I am, having to either resort to forking the SPF specification, or refactor my HTML views just to hide the scripts into one of the non-top-level elements for no particular reason.

Is there any chance of making the required magic more explicit [here](https://github.com/ractivejs/rcu/blob/master/src/parse.js#L49) and perhaps require a special marker class, say `<script class="componentExports">components.exports = { ... }</script>` for the script that is supposed to contain the directive?
I really feel this will make more sense, as it would signify that there exist some special syntax requirements and assumptions in that script. The framework will be adopted more widely if it does not put new restrictions to the existent expressibility (although I do think Ractive has been the very best at practicing it!).

If you guys agree, I am happy to write a PR that does this in a backwards compatible way, as I realize it is a must due to existent implementations.

Thanks for considering!

**Comment by fskreuz** [comment]
> still has this rough edge of only allowing a single top level `<script>` element on single-file components here.

Actually, there's [documentation about the component spec](https://github.com/ractivejs/component-spec).

There is [a spec for how component files are structured](https://github.com/ractivejs/component-spec/blob/master/authors.md). Summarized, it's one `<script>` which contains all your scripts and the component definition, `<styles>` are concatenated, and anything outside the two is considered markup.

Seeing that you are in rcu, you're probably implementing a tool. [There's a guide for building tools as well](https://github.com/ractivejs/component-spec/blob/master/implementers.md).

> Is there any chance of making the required magic more explicit here and perhaps require a special marker class, say <script class="componentExports">components.exports = { ... }</script> for the script that is supposed to contain the directive?

I'm interested on how you are using rcu and why you need multiple `<script>` elements. Care to share your case? :smile:

**Comment by zlamma** [comment]
I'm using `Ractive.load` to load various preexistent partial HTML views into a container (hence they don't always have a single wrapping root element, to allow the layout, including the look of the container, to be provided completely by the hosting page) and I want to make it possible for 'some of them, when needed, to utilize the goodness of Ractive. It started throwing in rcu on some files because, e.g. some had content like:
```html
<script src="code_for_some_odl_school_js_article_dynamics.js"></script>
<p>Lorem ipsum...</p>
<p>Lorem ipsum... <script>Some.Cool.Dynamic.Behavior.The.Old.School.Way()</script>Lorem ipsum...</p>
<p>Lorem ipsum... {{In}} {{Future}} {{Id}} {{Like}} {{To}} {{Allow}} {{Some}} {{Really}} {{Cool}} {{Ractive}} {{Content}} {{Too}} Lorem ipsum...</p>
<p>Lorem ipsum...</p>
```
Note that here I don't even have more than one script. I just don't have a `component.exports`... Yet... Or ever... Because in my case, some of my views will actually not have any `component.exports` and still take advantage of two-way-binding, because the loader of the partials will provide some standard `data` by doing `extend` on the component constructor after `Ractive.load`, and only then it will run it with an `el`.
So, in my case, it actually started throwing [here](https://github.com/ractivejs/ractive-load/blob/master/dist/ractive-load.js#L151) on `f[0]` being undefined, because rcu doesn't even expect that there will be a `src`-based empty script tag (it wants to eval contents).


Introducing a simple marker for the 'special' script would keep Ractive SPCs really just a graceful superset of plain old HTML.

**Comment by fskreuz** [comment]
Aha! There's the problem. You don't exactly have components. What you have are just regular templates that happen to have script elements. `Ractive.load` throws up because rcu doesn't know how to handle this scenario.

This isn't a component-spec issue, this is an rcu issue so it's better to create an issue on the [rcu repo](https://github.com/ractivejs/rcu/issues).

@Rich-Harris

**Comment by slawomir-brzezinski-at-travcorp** [comment]
Well, `<script>` [is optional](https://github.com/ractivejs/component-spec/blob/master/authors.md#script-tags-and-componentexports-optional) in a component, so one could also say they are components.

The reason why I am raising this in _component-spec_ is that I am wondering whether you guys would be interested in a comprehensive solution that will not just have an exception for scripts with `src`, but one that will allow _any partial html_ to be a Ractive component, even one that has inline scripts.
The only solution I can think of is having some markup class for that special `<script>` that get's evaled. The other inline scripts should be treated like content and executed upon adding all of it to the DOM.

**Comment by zlamma** [comment]
Well, `<script>` [is optional](https://github.com/ractivejs/component-spec/blob/master/authors.md#script-tags-and-componentexports-optional) in a component, so one could also say they are components.

The reason why I am raising this in _component-spec_ is that I am wondering whether you guys would be interested in a comprehensive solution that will not just have an exception for scripts with `src`, but one that will allow _any partial html_ to be a Ractive component, even one that has inline scripts.
The only solution I can think of is having some markup class for that special `<script>` that get's evaled. The other inline scripts should be treated like content and executed upon adding all of it to the DOM.

**Comment by ghost** [comment]
Closing this. Loading scripts inside the template is code smell. If it's code that the component depends on, it's better to declare it as a module and load it as a dependency.

**Comment by zlamma** [comment]
@fskreuz too bad. But must say that applying a green-field-Ractive-everywhere argument of code smell is uncalled for.

The change would simply give Ractive interoperability with standard HTML, be it from pre-existent legacy content, or simply written in a tech-agnostic vanilla HTML.
No hard feelings, but I thought it would be of interest for a framework that:

> ... works for you, not the other way around. It doesn't have an opinion about the other tools you want to use with it. It also adapts to the approach you want to take. You're not locked-in to a framework-specific way of thinking. Should you hate one of your tools for some reason, you can easily swap it out for another and move on with life.

**Comment by ghost** [comment]
[A similar issue came up a few days ago](https://github.com/ractivejs/ractive/issues/3125), and things like this can lead to unintended side-effects. A simple scenario would be loading jQuery as a script in the template of a component. Doing it this way would cause the script to re-evaluate every time an instance of this component is created. Do you _really_ want jQuery to be evaluated multiple times?

There's also little incentive using this syntax as a mechanism for module management since 1) The spec already does CJS-like modules with `require` and `component.exports` and 2) moving forward, there's the ES module syntax - both of which can be done by sticking a `<script>` and doing either either CJS `require` or ES `import` (when using https://github.com/ractivejs/ractive-bin-loader or https://github.com/ractivejs/rollup-plugin-ractive-bin for the latter).

I'll re-open the issue so that it's open to discussion. You can also reach everyone at https://gitter.im/ractivejs/ractive should you want to talk this over with other Ractive users.

**Comment by zlamma** [comment]
@fskreuz thanks for reconsidering. I shall strive to find time to make my points further.

As to your concerns, I'm well aware of the `</script>` problem, but I don't see how this proposal makes the problem any worse, so I wouldn't want to even digress to it.

> Do you really want jQuery to be evaluated multiple times?

Remember that I'm talking about HTML partials. As such, they must already deal with multi-tenancy problems and not load libraries via an outright `<script>`. That's regardless whether composition employs Ractive, another framework, or even something server-side or compile-time. They'd be using all the known arsenal for that - fixed list of 3rd party libs on the layout page, deferred page header building, JS modules, lately the native ones.
The only scripts you'd find in HTML partials are actually the ones that are very much expected to execute for every occurrence, since this is what merely uses the libraries to make the specific HTML nodes alive.

**Comment by ghost** [comment]
Closed in favor of a larger change that will more or less involve something similar https://github.com/ractivejs/component-spec/issues/18

**Comment by zlamma** [comment]
Just for reference, as per [this chat conversation of ours](https://gitter.im/ractivejs/ractive?at=5a833dfe7084124a34725b28), the change won't involve anything similar.  

The new component format is actually moving away from interoperability with freely authored HTML, as it introduces requirement of a special structure of the component, in that it needs to comprise of special elements, whereas the old format had only a special requirement that if it contained a top level `<script>` element, it needed to be one with (`component.exports`) (but [it could have none](https://github.com/ractivejs/component-spec/issues/14#issuecomment-180257256)), which was still was compatible with many freeform HTML partials.

This means that the closing is rather due to the whole feature getting dropped.

Too bad for me, but hey, life goes on :)
