### ISSUE TITLE
other way around ?

### ISSUE THREAD

**Issue by seriousme** [ractivejs/component-spec#15]
Just out of curiosity :-)

Following this spec an author would write a HTML file with script and style tags, which is then parsed by loaders to create javascript.

Wouldn't it be more easy to create javascript with an accompanying HTML file and have the javascript require the HTML ?
E.g. like its done at: http://paquitosoftware.com/ractive-js-tutorial-creating-the-barebones/

```
import Ractive from 'ractive';  
import Template from '../../views/layout/search-user.html';

var SearchGithub = Ractive.extend({  
    isolated: true,
    template: Template,

    oninit() {
        this.on('searchUser', (rEvent) => {
            rEvent.original.preventDefault();

            let username = rEvent.context.query;

            console.log('This is the user you want to look up:', username);
        });
    },

    data: {
        query: ''
    }
});

export default SearchGithub;  
```
This looks more natural to me and does not require all kinds of special loaders to parse HTML with script tags to javascript.

I'm curious to learn what the downside of this approach is in your view.

**Comment by fskreuz** [comment]
The fun thing about Ractive is *you do it the way you want*. There's no right or wrong. However, I've gone through that path of yours before, and it wasn't fun when I did that.

- You'll now have to worry about 2 files.
- You'll now have to worry where to put the files, whether they sit next to each other or separately.
- Naming the files will be hard (naming was always hard in programming).
- When moving files, you'll have twice the problem (two module paths to update).
- Most of the time, components never share templates thus separation isn't really necessary.

However, component files aren't always the best solution in all cases. In my case, my goal was to write vanilla JS with no funky convention (no AMD boilerplate, no Common JS, single-file). Now I just write templates like the following. 

```js
import Ractive from 'ractive';

export default Ractive.extend({
  template: `
    <div>stuff</div>
  `,
  css: `
    div { /* styles */ }
  `,
  oninit(){
    // init code
  }
  // other stuff
});
```

Still in a single file, template and styles are inlined but still clearly separated, all vanilla JS. For tools, I use Gobble, Rollup and Babel. I'm aware that I cannot take advantage of compile-time optimizations for Ractive (like pre-compiled templates and minified CSS), but that wasn't my goal. Again, *you do it the way you want*.

**Comment by seriousme** [comment]
Thx for the response. I do like the freedom provided by ractive, one can make a project as complex or simple as needed instead of being locked into a one-size fits all.

Nice to see you share my pref for vanilla. Your way of working looks quite nice as well. 

Thx for sharing !
