### ISSUE TITLE
RFC: Version 2 format

### ISSUE THREAD

**Issue by fskreuz** [ractivejs/component-spec#18]
Proposal to expand the current component file format to be able to support more workflows and languages. Note that this only talks about the component file's _format_. How this is implemented and how much gets implemented is still loader-specific.

## Container elements

The goal is to simplify both authoring as well as parsing of a component file.

```
external component      - <link rel="component" href="./path/to/component" id="MyComponent">
external partial        - <link rel="partial" href="./path/to/partial" id="ThatPartial">
external style (css)    - <link rel="style" type="ractive/style" href="./path/to/css/style">
external style (script) - <link rel="style" type="ractive/script" href="./path/to/js/style">

template                - <template>
partial                 - <template id="foo">

style (css)             - <style>
style (script)          - <style type="ractive/script">

component definition    - <script>
```

Expanding on the more drastic changes:

- `<template>` now surrounds the template, to be consistent with styles and scripts. These "container" elements facilitate support for writing in languages _other than_ HTML, CSS and JS (i.e. Jade, SCSS, TS) by defining clear boundaries when these snippets start and end.

- `<link>` is now used to declare all external resources. This way, you don't have to confuse yourself whether to use `<link href>` or `<script src>`.

- `<style type="ractive/script">` to support function-style `css`. Your editor will probably yell at you, but then it's nothing a highlighter can't fix (a future goal).

## Component definition format

The goal is to modernize and make consistent the component file format.

```html
<!-- CJS -->
<link ... />
<template> ... </template>
<style> ... </style>

<script>
  const jQuery = require('jquery')

  module.exports = {
    ...
  }
</script>

<!-- ESM -->
<link ... />
<template> ... </template>
<style> ... </style>

<script>
  import jQuery  from 'jquery'

  export default {
    ...
  }
</script>

```

Summary of changes:

- Change `component.exports` to `module.exports` to be more coherent with CJS.
- Allow writing in ESM, with the default export being the init options.
- Like before, markup options take precedence over ones defined in the script options.
- CJS will be the universal, run-immediately format. ESM, for the forseeable future, will require a compile.

**Comment by ghost** [comment]
ugh... I thought I assigned reviewers. 🤦‍♂️ issues don't have reviewers.

**Comment by fskreuz** [comment]
Pondering about backwards compat a bit:

```
# Ractive-specific (browser should ignore)

external component      - <link rel="component" href="./path/to/component" id="MyComponent">
external partial        - <link rel="partial" href="./path/to/partial" id="ThatPartial">
external style (css)    - <link rel="style" href="./path/to/css/style" type="ractive/style">
external style (script) - <link rel="style" href="./path/to/js/style" type="ractive/script">

style (css)             - <style type="ractive/style">
style (script)          - <style type="ractive/script">

component definition    - <script type="ractive/script">

# Middle-ground (works on both)

template                - <div id="default">
partial                 - <div id="somethingNotDefault">

# Regular HTML (parser should ignore)

regular link            - <link rel="anythingNotFromAbove" href="./path/to/something">
regular style           - <style [type="?"]>
regular script          - <script [type="?"]>
regular external script - <script [type="?"] src="path/to/js">
```
Changes:

- Top-level `<div>`s instead of `<template>` for template and partial to allow HTML interop. 
    - These containers won't make it to the page when using loaders.
    - These render a style-less container for plain HTML.
    - A `<div>`  id'ed "default" is the main template. Any other `<div>` that has an id other than "default" becomes partials. `<div>`s without an ID is invalid.
- For the shared elements (`<script>` and `<style>`)
    - A `type="ractive/*"` will be honored by parser but should be ignored by the browser.
    - A `type="text/*"` should be ignored by the parser, but the browser should be able to read.
    - I am not sure how the browser handles unknown `rel`s.
- All of the above means that the component markup should be _more specific_ since plain HTML will be taking up default expectations (optional types, known types). This means `rel` and `type` become required attributes for component markup.

**Comment by fskreuz** [comment]
The biggest roadblock to this format that's related to #14 is just `<template>` and a singular `<script>`. Here's a minor change:

- ID'ed `<div>` instead of `<template>`
    - The top-level `<div>`s will not make it to through the parser.
    - Should just be an unstyled `<div>` when viewed directly on a browser.
- A typed `<script>` for regular scripts, untyped for SFC component def.
    - Should just work when viewed directly on a browser.
    - The parser can ignore typed scripts, and honor the one without a type.
    - Non-SFC workflows should add a harmless `type`.

The other things like `<link rel="stylesheet">` should just work, while the others with `ractive/*` as type should be ignored by the browser right off the bat.

```
# iirc, browsers ignore unknown rels. These are good to go.
external component      - <link rel="component" href="./path/to/component" id="MyComponent">
external partial        - <link rel="partial" href="./path/to/partial" id="ThatPartial">
external style (css)    - <link rel="style" href="./path/to/css/style" type="ractive/style">
external style (script) - <link rel="style" href="./path/to/js/style" type="ractive/javascript">

# Should work for both
template                - <div id="default">
partial                 - <div id="somethingNotDefault">

# Untyped works for both scenarios, browser ignores the unknown type
style (css)             - <style>
style (script)          - <style type="ractive/javascript">

# Both work for both, but it's assumed `<script>` is the component, the typed one as regular.
component definition    - <script>
regular script          - <script type="text/javascript">
```

**Comment by ghost** [comment]
Closing this for now. The additional elements multiplies effort by the number of loaders that need to implement this. Currently, there's rollup, webpack, systemjs\*, browser and nodejs loaders [in the monorepo work](https://github.com/fskreuz/ractive-monorepo) - all of which require very different inlining routines. Besides, Vue does not appear to have issues having only 3 elements in their SFC. Ractive's `<link>` is already a generous addition.

Just keeping things simple 😉 

<sub>* on the verge of dropping. There's already a browser loader for runtime, and Webpack/Rollup for build time.</sub>
