### ISSUE TITLE
Extend component spec to allow for importinig partials using <link>

### ISSUE THREAD

**Issue by avoto** [ractivejs/component-spec#19]
Today I find myself adding a lot of inline partials to various components. This makes the component code difficult to read and follow.

That said I thought that It would be very nice if the component spec allows for a new ```<link rel="ractivePartial" href="path_to_partial.html" name="myPartial">``` which essentially ads the partial into constructor.partials (component.exports).

Lastly I am keen on making the change (here in terms of documenting it and in the RCU repo). @fskreuz if I do so, should I just make a pull request with you as a reviewer?

Of course, I am not going to go ahead with any work until this gets finalized - eg. what should the format of the new partial <link> be, etc.

**Comment by ghost** [comment]
I'm cool with reviewing. We just need everyone to chime in.

Until everyone weighs in, I have this question though: Why aren't they/can't they be standalone components? Why are they just partials? Having a component consume a bunch of partials, to me, is a sign that the component is getting big and needs to break off to smaller components. 🤔

**Comment by avoto** [comment]
Well, I am not 100% sure, but aren’t components just Ractive instances and partials more lightweight? 
Also, partials are not “isolated” as component are by default, so replacing them with components will require.setting isolated to false on each one of them, etc.

In my usecase partials are needed because I have no need of a the component’s infrastructure: events, own scope, etc. 

On your other question / note the reason for having many of them is purely driven by the complexity of the requirements, which is also why I was avoiding using components, being afraid that 1000 component (Ractive) instances will make the page really resource intensive.

Lastly because partials are a prime citizen of the Ractive ecosystem I thought it would be a nice improvement, making partials also reusable.

I am quite open for a discussion, as long as it can yield some solution to externalizing them. One idea that crossed my mind earlier is to have a component which contains all the partials for a specific screen which is then included when these are needed... but that seemed less attractive than having the ability to just include a set of reusable partials via a link tag.

**Comment by ghost** [comment]
Throwing this into gitter to get everyone's attention. 😁

**Comment by ghost** [comment]
To engage everyone into a conversation, I shall take the preliminary poking of the bear and kicking of the beehive:

## If we're taking this route...

Suggesting changing the syntax to something like `<link rel="ractive" type="partial">`. This indicates the linked document is Ractive-related, and of partial type. This, in effect, would require components be `type="component"`.

We'd also need to decide on an extension. Tools like Webpack and Gobble use extension-matching to determine which files get processed by which tools. `.html` or `.ractive.html` would incorrectly parse the external partial as a component. I've used Gobble to turn `.ractive.html` component files into `.js` modules, and have Rollup bundle them like any other JS.

## Why we might not go this route...

If it's a performance issue regarding components, we should solve _that_ problem instead. If there's anything I don't like about the current trends in JavaScript (or programming in general), it's fixing problems by throwing more software, process or structure at it. Adding more moving parts just makes more room for error.

Also, the concept is somewhat strange. I don't see other frameworks doing something similar, which hints that they might not have a need for such or have a solution that doesn't require such. Maybe we can look at other frameworks to see 1) how they're getting around fat components and 2) how they're reusing large swathes of redundant template.

Also, long code is never a problem. That's what code folding was designed for. 😁

**Comment by avoto** [comment]
@fskreuz hence, the loading of these works fine with require() I think I will close this for now.
