### ISSUE TITLE
Get CSS namespace for dom element created outside of ractive

### ISSUE THREAD

**Issue by timshannon** [ractivejs/component-spec#3]
I have a component using jqueryui - draggable, and there is the option to have what you're dragging be a dom element created at the time of dragging (http://api.jqueryui.com/draggable/#option-helper).

The problem is my component's CSS doesn't apply to this node, because it doesn't have the ```data-rvcguid``` attribute.

Can I look that up somewhere and add it manually to my node, or make ractive aware of this new node in some way?

**Comment by martypdx** [comment]
If you don't need the css scoping, you can just turn it off via the [`noCssTransform` option](http://docs.ractivejs.org/latest/options#noCssTransform).

If you need to keep the css scoping, you'd have to use some undocumented properties (all usual warnings apply) to create the attribute:

```js
// for edge, given an html node and component instance c:
node.setAttribute('data-ractive-css', c.constructor._guid);
```

**Comment by timshannon** [comment]
I wonder if there's a better way than using undocumented properties.

Is there anyway to return a node out of a ractive instance?  In the end I need a function that returns a node.

If I could create a node using my component ractive and return it, then that would solve my issue as well.

There's ractive.render which allows me to target an existing node, but do I have any options to render to a node in memory and return it?

**Comment by martypdx** [comment]
@timshannon I'm not really following you, but my best guess is that you want the "helper" drag node decorated with the attribute so component style will work? 

Could you render the helper node in your template, then use `ractive.find('#helper')` to return that node (possibly need to detach via `node.parentNode.removeChild(node)`)?

**Comment by timshannon** [comment]
yeah, that's what I'm after.  I got a few options you've given me to try.

Thanks for the help,
