### ISSUE TITLE
single-page component with <script> does not work

### ISSUE THREAD

**Issue by Centaur** [ractivejs/component-spec#4]
ractive 0.6.1, ractive-load 0.4.0 , all installed using bower. The `HelloWorld` example works but once the `<script>` tag is added to the component html, it does not work, only a blank page.

**Comment by Rich-Harris** [comment]
That's odd - what is inside the `<script>` tag? Maybe it's causing an error. Because `Ractive.load()` returns a promise, errors will get swallowed - I've found the easiest way to deal with errors in promises is this:

```js
Ractive.load( 'helloworld.html' )
.then( function ( HelloWorld ) {
  // render...
})
.catch( function ( err ) {
  // if we re-throw, it gets swallowed again, so
  // instead we setTimeout. That way we get
  // to see the full stack, etc
  setTimeout( function () { throw err; });
});
```

Could you try that and see what the error message is? Thanks

**Comment by Centaur** [comment]
My bad. Seems I have got some browser cache issue. But this non-issue is not useless after all. Thank you very much for giving information on how to debug a loaded component!
