### ISSUE TITLE
Fail at parsed.v check (RactiveJS 0.6.1)

### ISSUE THREAD

**Issue by mefjuu** [ractivejs/component-spec#5]
There is a problem with the following `parsed.v` check in ractive-load (or rcv) using Ractive v.0.6.1, `that gives parsed.v === 2`:

```
if (parsed.v !== 1) {
throw new Error('Mismatched template version! Please ensure you are using the latest version of Ractive.js in your build process as well as in your app');
}
```

**Comment by martypdx** [comment]
See https://github.com/ractivejs/rvc/issues/7#issuecomment-75072419
